<?php ?><!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php wp_title( '|', true, 'right' ); ?></title>
	<meta name="msvalidate.01" content="5C2013943AE766BC22B45DC541B3B4E1" />
	<link rel="profile" href="http://gmpg.org/xfn/11">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/css/ie10-viewport-bug-workaround.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,500,700">
	<!--[if lt IE 9]>
	<script src="<?php echo get_template_directory_uri(); ?>/js/html5.js"></script>
	<![endif]-->
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "e-tec Computer Services",
	  "telephone" : "07977 697099",
	  "email" : "support@e-tecpc.co.uk",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "River Mill Business Centre, Park Road",
	    "addressLocality" : "Dukinfield",
	    "addressRegion" : "Cheshire",
	    "postalCode" : "SK16 5LR"
	  },
	  "url" : "http://www.e-tecpc.co.uk/"
	}
	</script>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89934430-1', 'auto');
  ga('send', 'pageview');

	</script>
	<?php wp_head(); ?>
</head>

<body>
		<header>
	    <nav class="navbar navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <a class="navbar-brand" href="/"><img src="<?php echo get_template_directory_uri(); ?>/images/etec-logo.png" class="hidden-xs" alt="e-tec Computer Services" Title="e-tec Computer Services" width="168" height="56"><img src="<?php echo get_template_directory_uri(); ?>/images/etec-logo.png" class="visible-xs-block" alt="e-tec Computer Services" Title="e-tec Computer Services" width="84" height="28"></a>
	        </div>
	        <div id="primary-navigation" class="site-navigation primary-navigation" role="navigation">
					<button class="menu-toggle"><?php _e( 'Primary Menu', 'twentyfourteen' ); ?></button>
					<a class="screen-reader-text skip-link" href="#content"><?php _e( 'Skip to content', 'twentyfourteen' ); ?></a>
					<?php wp_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => 'nav-menu', 'menu_id' => 'primary-menu' ) ); ?>
				</div>
	      </div>
	    </nav>
		</header>